"""initial database schema

Revision ID: 335b81056d71
Revises: 
Create Date: 2026-10-01 06:16:20.767218
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

revision = '335b81056d71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended')", name=op.f('ck_organizations_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name='uq_organizations_slug'),
    schema='fleetguard'
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name='uq_permissions_code'),
    schema='fleetguard'
    )
    op.create_table('drivers',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('external_driver_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('license_class', sa.String(length=40), nullable=True),
    sa.Column('license_region', sa.String(length=80), nullable=True),
    sa.Column('license_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name=op.f('ck_drivers_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_drivers_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_drivers_organization_id'),
    schema='fleetguard'
    )
    op.create_index('ix_drivers_organization_status', 'drivers', ['organization_id', 'status'], unique=False, schema='fleetguard')
    op.create_table('fleets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'archived')", name=op.f('ck_fleets_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_fleets_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleets')),
    sa.UniqueConstraint('organization_id', 'fleet_code', name='uq_fleets_organization_code'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_fleets_organization_id'),
    schema='fleetguard'
    )
    op.create_index('ix_fleets_organization_status', 'fleets', ['organization_id', 'status'], unique=False, schema='fleetguard')
    op.create_table('knowledge_documents',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('fault_code', sa.String(length=40), nullable=True),
    sa.Column('vehicle_make', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name='fk_knowledge_documents_organization', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    schema='fleetguard'
    )
    op.create_index('ix_knowledge_documents_fault_code', 'knowledge_documents', ['fault_code'], unique=False, schema='fleetguard')
    op.create_index('ix_knowledge_documents_type', 'knowledge_documents', ['document_type', 'created_at'], unique=False, schema='fleetguard')
    op.create_table('roles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_roles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_roles_organization_id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_roles_organization_name'),
    schema='fleetguard'
    )
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='trial', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seat_limit', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('trial', 'active', 'past_due', 'cancelled', 'expired')", name=op.f('ck_subscriptions_status')),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name=op.f('ck_subscriptions_subscription_dates')),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_subscriptions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    schema='fleetguard'
    )
    op.create_index('ix_subscriptions_organization_status', 'subscriptions', ['organization_id', 'status'], unique=False, schema='fleetguard')
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='invited', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled', 'invited')", name=op.f('ck_users_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_users_organization_id'),
    schema='fleetguard'
    )
    op.create_index('ix_users_organization_status', 'users', ['organization_id', 'status'], unique=False, schema='fleetguard')
    op.create_index('uq_users_organization_email_lower', 'users', ['organization_id', sa.text('lower(email)')], unique=True, schema='fleetguard')
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('request_id', sa.String(length=160), nullable=True),
    sa.Column('result', sa.String(length=30), server_default='success', nullable=False),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['fleetguard.users.organization_id', 'fleetguard.users.id'], name='fk_audit_actor_tenant', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='fleetguard'
    )
    op.create_index('ix_audit_organization_time', 'audit_logs', ['organization_id', sa.text('occurred_at DESC')], unique=False, schema='fleetguard')
    op.create_index('ix_audit_request_id', 'audit_logs', ['request_id'], unique=False, schema='fleetguard')
    op.create_index('ix_audit_resource_time', 'audit_logs', ['organization_id', 'resource_type', 'resource_id', sa.text('occurred_at DESC')], unique=False, schema='fleetguard')
    op.create_table('driver_risk_summaries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('calculation_source', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')", name=op.f('ck_driver_risk_summaries_risk_level')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_driver_risk_summaries_score_range')),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_driver_risk_summaries_window_dates')),
    sa.ForeignKeyConstraint(['organization_id', 'driver_id'], ['fleetguard.drivers.organization_id', 'fleetguard.drivers.id'], name='fk_driver_risk_driver_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_risk_summaries')),
    sa.UniqueConstraint('organization_id', 'driver_id', 'window_start', 'window_end', name='uq_driver_risk_window'),
    schema='fleetguard'
    )
    op.create_index('ix_driver_risk_latest', 'driver_risk_summaries', ['organization_id', 'driver_id', sa.text('window_end DESC')], unique=False, schema='fleetguard')
    op.create_table('fleet_cost_summaries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('distance_km IS NULL OR distance_km >= 0', name=op.f('ck_fleet_cost_summaries_distance')),
    sa.CheckConstraint('period_end > period_start', name=op.f('ck_fleet_cost_summaries_period_dates')),
    sa.CheckConstraint('total_cost IS NULL OR total_cost >= 0', name=op.f('ck_fleet_cost_summaries_total_cost')),
    sa.ForeignKeyConstraint(['organization_id', 'fleet_id'], ['fleetguard.fleets.organization_id', 'fleetguard.fleets.id'], name='fk_fleet_cost_fleet_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleet_cost_summaries')),
    sa.UniqueConstraint('organization_id', 'fleet_id', 'period_start', 'period_end', name='uq_fleet_cost_period'),
    schema='fleetguard'
    )
    op.create_index('ix_fleet_cost_latest', 'fleet_cost_summaries', ['organization_id', 'fleet_id', sa.text('period_end DESC')], unique=False, schema='fleetguard')
    op.create_table('fleet_risk_summaries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('vehicle_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('high_risk_vehicle_count', sa.Integer(), nullable=True),
    sa.Column('calculation_source', sa.String(length=40), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')", name=op.f('ck_fleet_risk_summaries_risk_level')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_fleet_risk_summaries_score_range')),
    sa.CheckConstraint('vehicle_count >= 0 AND (high_risk_vehicle_count IS NULL OR high_risk_vehicle_count >= 0)', name=op.f('ck_fleet_risk_summaries_vehicle_counts')),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_fleet_risk_summaries_window_dates')),
    sa.ForeignKeyConstraint(['organization_id', 'fleet_id'], ['fleetguard.fleets.organization_id', 'fleetguard.fleets.id'], name='fk_fleet_risk_fleet_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleet_risk_summaries')),
    sa.UniqueConstraint('organization_id', 'fleet_id', 'window_start', 'window_end', name='uq_fleet_risk_window'),
    schema='fleetguard'
    )
    op.create_index('ix_fleet_risk_latest', 'fleet_risk_summaries', ['organization_id', 'fleet_id', sa.text('window_end DESC')], unique=False, schema='fleetguard')
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['fleetguard.knowledge_documents.id'], name='fk_knowledge_chunks_document', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunks_document_index'),
    schema='fleetguard'
    )
    op.create_index('ix_knowledge_chunks_document', 'knowledge_chunks', ['document_id', 'chunk_index'], unique=False, schema='fleetguard')
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, schema='fleetguard', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('role_permissions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'role_id'], ['fleetguard.roles.organization_id', 'fleetguard.roles.id'], name='fk_role_permissions_role_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['fleetguard.permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'role_id', 'permission_id', name=op.f('pk_role_permissions')),
    schema='fleetguard'
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False, schema='fleetguard')
    op.create_table('user_roles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'role_id'], ['fleetguard.roles.organization_id', 'fleetguard.roles.id'], name='fk_user_roles_role_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['fleetguard.users.organization_id', 'fleetguard.users.id'], name='fk_user_roles_user_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id', 'role_id', name=op.f('pk_user_roles')),
    schema='fleetguard'
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False, schema='fleetguard')
    op.create_table('vehicles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=60), nullable=False),
    sa.Column('powertrain_type', sa.String(length=30), nullable=False),
    sa.Column('fuel_type', sa.String(length=40), nullable=True),
    sa.Column('fuel_capacity_l', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("powertrain_type IN ('ice', 'hybrid', 'plug_in_hybrid', 'electric', 'other')", name=op.f('ck_vehicles_powertrain')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance', 'retired')", name=op.f('ck_vehicles_status')),
    sa.CheckConstraint('battery_capacity_kwh IS NULL OR battery_capacity_kwh > 0', name=op.f('ck_vehicles_battery_capacity')),
    sa.CheckConstraint('fuel_capacity_l IS NULL OR fuel_capacity_l > 0', name=op.f('ck_vehicles_fuel_capacity')),
    sa.CheckConstraint('model_year IS NULL OR model_year BETWEEN 1886 AND 2200', name=op.f('ck_vehicles_model_year')),
    sa.ForeignKeyConstraint(['organization_id', 'fleet_id'], ['fleetguard.fleets.organization_id', 'fleetguard.fleets.id'], name='fk_vehicles_fleet_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_vehicles_organization_id'),
    sa.UniqueConstraint('organization_id', 'vin', name='uq_vehicles_organization_vin'),
    schema='fleetguard'
    )
    op.create_index('ix_vehicles_organization_fleet', 'vehicles', ['organization_id', 'fleet_id'], unique=False, schema='fleetguard')
    op.create_index('ix_vehicles_organization_status', 'vehicles', ['organization_id', 'status'], unique=False, schema='fleetguard')
    op.create_table('alerts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'low', 'medium', 'high', 'critical')", name=op.f('ck_alerts_severity')),
    sa.CheckConstraint("status IN ('active', 'acknowledged', 'resolved', 'dismissed')", name=op.f('ck_alerts_status')),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= event_at', name=op.f('ck_alerts_resolved_after_event')),
    sa.ForeignKeyConstraint(['organization_id', 'acknowledged_by_user_id'], ['fleetguard.users.organization_id', 'fleetguard.users.id'], name='fk_alerts_acknowledged_user_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'driver_id'], ['fleetguard.drivers.organization_id', 'fleetguard.drivers.id'], name='fk_alerts_driver_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'fleet_id'], ['fleetguard.fleets.organization_id', 'fleetguard.fleets.id'], name='fk_alerts_fleet_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_alerts_vehicle_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_alerts_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_alerts_organization_id'),
    schema='fleetguard'
    )
    op.create_index('ix_alerts_fleet_status_severity', 'alerts', ['organization_id', 'fleet_id', 'status', 'severity'], unique=False, schema='fleetguard')
    op.create_index('ix_alerts_organization_status_severity_time', 'alerts', ['organization_id', 'status', 'severity', sa.text('created_at DESC')], unique=False, schema='fleetguard')
    op.create_index('ix_alerts_recent', 'alerts', ['organization_id', sa.text('created_at DESC')], unique=False, schema='fleetguard')
    op.create_index('ix_alerts_vehicle_created', 'alerts', ['organization_id', 'vehicle_id', sa.text('created_at DESC')], unique=False, schema='fleetguard')
    op.create_table('maintenance_plans',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('maintenance_type', sa.String(length=80), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('interval_distance_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('plan_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'retired')", name=op.f('ck_maintenance_plans_status')),
    sa.CheckConstraint('fleet_id IS NOT NULL OR vehicle_id IS NOT NULL', name=op.f('ck_maintenance_plans_target_required')),
    sa.CheckConstraint('interval_days IS NULL OR interval_days > 0', name=op.f('ck_maintenance_plans_interval_days')),
    sa.CheckConstraint('interval_distance_km IS NULL OR interval_distance_km > 0', name=op.f('ck_maintenance_plans_interval_distance')),
    sa.ForeignKeyConstraint(['organization_id', 'fleet_id'], ['fleetguard.fleets.organization_id', 'fleetguard.fleets.id'], name='fk_maintenance_plans_fleet_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_maintenance_plans_vehicle_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['fleetguard.organizations.id'], name=op.f('fk_maintenance_plans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_plans')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_maintenance_plans_organization_id'),
    schema='fleetguard'
    )
    op.create_index('ix_maintenance_plans_fleet_status', 'maintenance_plans', ['organization_id', 'fleet_id', 'status'], unique=False, schema='fleetguard')
    op.create_index('ix_maintenance_plans_vehicle_status', 'maintenance_plans', ['organization_id', 'vehicle_id', 'status'], unique=False, schema='fleetguard')
    op.create_table('maintenance_records',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=80), nullable=False),
    sa.Column('service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('service_provider', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('service_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'scheduled', 'completed', 'cancelled')", name=op.f('ck_maintenance_records_status')),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name=op.f('ck_maintenance_records_cost')),
    sa.CheckConstraint('odometer_km IS NULL OR odometer_km >= 0', name=op.f('ck_maintenance_records_odometer')),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_maintenance_vehicle_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_records')),
    schema='fleetguard'
    )
    op.create_index('ix_maintenance_vehicle_service', 'maintenance_records', ['organization_id', 'vehicle_id', sa.text('service_at DESC')], unique=False, schema='fleetguard')
    op.create_table('trips',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('start_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('fuel_used_l', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('energy_used_kwh', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'cancelled')", name=op.f('ck_trips_status')),
    sa.CheckConstraint('distance_km IS NULL OR distance_km >= 0', name=op.f('ck_trips_distance')),
    sa.CheckConstraint('end_latitude IS NULL OR end_latitude BETWEEN -90 AND 90', name=op.f('ck_trips_end_latitude')),
    sa.CheckConstraint('end_longitude IS NULL OR end_longitude BETWEEN -180 AND 180', name=op.f('ck_trips_end_longitude')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_trips_trip_dates')),
    sa.CheckConstraint('energy_used_kwh IS NULL OR energy_used_kwh >= 0', name=op.f('ck_trips_energy_used')),
    sa.CheckConstraint('fuel_used_l IS NULL OR fuel_used_l >= 0', name=op.f('ck_trips_fuel_used')),
    sa.CheckConstraint('start_latitude IS NULL OR start_latitude BETWEEN -90 AND 90', name=op.f('ck_trips_start_latitude')),
    sa.CheckConstraint('start_longitude IS NULL OR start_longitude BETWEEN -180 AND 180', name=op.f('ck_trips_start_longitude')),
    sa.ForeignKeyConstraint(['organization_id', 'driver_id'], ['fleetguard.drivers.organization_id', 'fleetguard.drivers.id'], name='fk_trips_driver_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_trips_vehicle_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    schema='fleetguard'
    )
    op.create_index('ix_trips_driver_started', 'trips', ['organization_id', 'driver_id', sa.text('started_at DESC')], unique=False, schema='fleetguard')
    op.create_index('ix_trips_vehicle_started', 'trips', ['organization_id', 'vehicle_id', sa.text('started_at DESC')], unique=False, schema='fleetguard')
    op.create_table('vehicle_driver_assignments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_source', sa.String(length=40), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name=op.f('ck_vehicle_driver_assignments_assignment_dates')),
    sa.ForeignKeyConstraint(['organization_id', 'driver_id'], ['fleetguard.drivers.organization_id', 'fleetguard.drivers.id'], name='fk_assignments_driver_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_assignments_vehicle_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_driver_assignments')),
    schema='fleetguard'
    )
    op.create_index('ix_assignments_driver_started', 'vehicle_driver_assignments', ['organization_id', 'driver_id', sa.text('starts_at DESC')], unique=False, schema='fleetguard')
    op.create_index('ix_assignments_vehicle_started', 'vehicle_driver_assignments', ['organization_id', 'vehicle_id', sa.text('starts_at DESC')], unique=False, schema='fleetguard')
    op.create_index('uq_assignments_active_driver', 'vehicle_driver_assignments', ['organization_id', 'driver_id'], unique=True, schema='fleetguard', postgresql_where=sa.text('ends_at IS NULL'))
    op.create_index('uq_assignments_active_vehicle', 'vehicle_driver_assignments', ['organization_id', 'vehicle_id'], unique=True, schema='fleetguard', postgresql_where=sa.text('ends_at IS NULL'))
    op.create_table('vehicle_risk_summaries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('calculation_source', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')", name=op.f('ck_vehicle_risk_summaries_risk_level')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_vehicle_risk_summaries_score_range')),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_vehicle_risk_summaries_window_dates')),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_vehicle_risk_vehicle_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_risk_summaries')),
    sa.UniqueConstraint('organization_id', 'vehicle_id', 'window_start', 'window_end', name='uq_vehicle_risk_window'),
    schema='fleetguard'
    )
    op.create_index('ix_vehicle_risk_latest', 'vehicle_risk_summaries', ['organization_id', 'vehicle_id', sa.text('window_end DESC')], unique=False, schema='fleetguard')
    op.create_table('alert_acknowledgements',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'alert_id'], ['fleetguard.alerts.organization_id', 'fleetguard.alerts.id'], name='fk_alert_acknowledgements_alert_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['fleetguard.users.organization_id', 'fleetguard.users.id'], name='fk_alert_acknowledgements_user_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_acknowledgements')),
    schema='fleetguard'
    )
    op.create_index('ix_alert_acknowledgements_alert_time', 'alert_acknowledgements', ['organization_id', 'alert_id', sa.text('acknowledged_at DESC')], unique=False, schema='fleetguard')
    op.create_table('maintenance_work_orders',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('work_order_number', sa.String(length=80), nullable=False),
    sa.Column('maintenance_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name=op.f('ck_maintenance_work_orders_priority')),
    sa.CheckConstraint("status IN ('open', 'scheduled', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_maintenance_work_orders_status')),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name=op.f('ck_maintenance_work_orders_estimated_cost')),
    sa.ForeignKeyConstraint(['organization_id', 'plan_id'], ['fleetguard.maintenance_plans.organization_id', 'fleetguard.maintenance_plans.id'], name='fk_work_orders_plan_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'vehicle_id'], ['fleetguard.vehicles.organization_id', 'fleetguard.vehicles.id'], name='fk_work_orders_vehicle_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_work_orders')),
    sa.UniqueConstraint('organization_id', 'work_order_number', name='uq_work_orders_organization_number'),
    schema='fleetguard'
    )
    op.create_index('ix_work_orders_due', 'maintenance_work_orders', ['organization_id', 'status', 'scheduled_for'], unique=False, schema='fleetguard')
    op.create_index('ix_work_orders_vehicle_status', 'maintenance_work_orders', ['organization_id', 'vehicle_id', 'status'], unique=False, schema='fleetguard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_orders_vehicle_status', table_name='maintenance_work_orders', schema='fleetguard')
    op.drop_index('ix_work_orders_due', table_name='maintenance_work_orders', schema='fleetguard')
    op.drop_table('maintenance_work_orders', schema='fleetguard')
    op.drop_index('ix_alert_acknowledgements_alert_time', table_name='alert_acknowledgements', schema='fleetguard')
    op.drop_table('alert_acknowledgements', schema='fleetguard')
    op.drop_index('ix_vehicle_risk_latest', table_name='vehicle_risk_summaries', schema='fleetguard')
    op.drop_table('vehicle_risk_summaries', schema='fleetguard')
    op.drop_index('uq_assignments_active_vehicle', table_name='vehicle_driver_assignments', schema='fleetguard', postgresql_where=sa.text('ends_at IS NULL'))
    op.drop_index('uq_assignments_active_driver', table_name='vehicle_driver_assignments', schema='fleetguard', postgresql_where=sa.text('ends_at IS NULL'))
    op.drop_index('ix_assignments_vehicle_started', table_name='vehicle_driver_assignments', schema='fleetguard')
    op.drop_index('ix_assignments_driver_started', table_name='vehicle_driver_assignments', schema='fleetguard')
    op.drop_table('vehicle_driver_assignments', schema='fleetguard')
    op.drop_index('ix_trips_vehicle_started', table_name='trips', schema='fleetguard')
    op.drop_index('ix_trips_driver_started', table_name='trips', schema='fleetguard')
    op.drop_table('trips', schema='fleetguard')
    op.drop_index('ix_maintenance_vehicle_service', table_name='maintenance_records', schema='fleetguard')
    op.drop_table('maintenance_records', schema='fleetguard')
    op.drop_index('ix_maintenance_plans_vehicle_status', table_name='maintenance_plans', schema='fleetguard')
    op.drop_index('ix_maintenance_plans_fleet_status', table_name='maintenance_plans', schema='fleetguard')
    op.drop_table('maintenance_plans', schema='fleetguard')
    op.drop_index('ix_alerts_vehicle_created', table_name='alerts', schema='fleetguard')
    op.drop_index('ix_alerts_recent', table_name='alerts', schema='fleetguard')
    op.drop_index('ix_alerts_organization_status_severity_time', table_name='alerts', schema='fleetguard')
    op.drop_index('ix_alerts_fleet_status_severity', table_name='alerts', schema='fleetguard')
    op.drop_table('alerts', schema='fleetguard')
    op.drop_index('ix_vehicles_organization_status', table_name='vehicles', schema='fleetguard')
    op.drop_index('ix_vehicles_organization_fleet', table_name='vehicles', schema='fleetguard')
    op.drop_table('vehicles', schema='fleetguard')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles', schema='fleetguard')
    op.drop_table('user_roles', schema='fleetguard')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions', schema='fleetguard')
    op.drop_table('role_permissions', schema='fleetguard')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks', schema='fleetguard', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_knowledge_chunks_document', table_name='knowledge_chunks', schema='fleetguard')
    op.drop_table('knowledge_chunks', schema='fleetguard')
    op.drop_index('ix_fleet_risk_latest', table_name='fleet_risk_summaries', schema='fleetguard')
    op.drop_table('fleet_risk_summaries', schema='fleetguard')
    op.drop_index('ix_fleet_cost_latest', table_name='fleet_cost_summaries', schema='fleetguard')
    op.drop_table('fleet_cost_summaries', schema='fleetguard')
    op.drop_index('ix_driver_risk_latest', table_name='driver_risk_summaries', schema='fleetguard')
    op.drop_table('driver_risk_summaries', schema='fleetguard')
    op.drop_index('ix_audit_resource_time', table_name='audit_logs', schema='fleetguard')
    op.drop_index('ix_audit_request_id', table_name='audit_logs', schema='fleetguard')
    op.drop_index('ix_audit_organization_time', table_name='audit_logs', schema='fleetguard')
    op.drop_table('audit_logs', schema='fleetguard')
    op.drop_index('uq_users_organization_email_lower', table_name='users', schema='fleetguard')
    op.drop_index('ix_users_organization_status', table_name='users', schema='fleetguard')
    op.drop_table('users', schema='fleetguard')
    op.drop_index('ix_subscriptions_organization_status', table_name='subscriptions', schema='fleetguard')
    op.drop_table('subscriptions', schema='fleetguard')
    op.drop_table('roles', schema='fleetguard')
    op.drop_index('ix_knowledge_documents_type', table_name='knowledge_documents', schema='fleetguard')
    op.drop_index('ix_knowledge_documents_fault_code', table_name='knowledge_documents', schema='fleetguard')
    op.drop_table('knowledge_documents', schema='fleetguard')
    op.drop_index('ix_fleets_organization_status', table_name='fleets', schema='fleetguard')
    op.drop_table('fleets', schema='fleetguard')
    op.drop_index('ix_drivers_organization_status', table_name='drivers', schema='fleetguard')
    op.drop_table('drivers', schema='fleetguard')
    op.drop_table('permissions', schema='fleetguard')
    op.drop_table('organizations', schema='fleetguard')
    # ### end Alembic commands ###